# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fd2e72633e1c595557535a69e5adf46b8dbb4bd979af396e7d8c312fd824c8e62ada7f4e4d222e342fd448d82501c728c8ca2170c023e14ffd006389a6cbd65

test:
  secret_key_base: 5ff173bd68c2f04f01c139790821b06e221e721e2258458376db79d5c95c0f61c543d1767532aec50ecb7731f6585b6a3d93efd25f91206eb5e7c7dd07425c88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
